### ISSUE TITLE
blend shape tracks don't work with SubdivMeshInstance3D

### ISSUE THREAD

**Issue by fire** [tefusion/godot-subdiv#18]
Verify if comment todo is still accurate.

**Comment by tefusion** [comment]
Well they don't exactly work as intended. The importer now just has that converter script included at https://github.com/tefusion/godot-subdiv/blob/b1a8cba7aed1fcb935991cf168cf053a760f4ee3/project/addons/godot_subdiv/subdiv_converter.gd#L33-L54.

The only real disadvantage I see right now is that the tracks aren't blue, since it prefixes all tracks with blendshape you'd have to actively try to make a problematic property. No idea if blend shape tracks otherwise actually work differently.

Edit: If you meant the actual comment there: In the AnimationPlayer for blend shape tracks the node gets casted to MeshInstance3D, cause SubdivMeshInstance3D doesn't inherit from MeshInstance this converter code needs to run. Imo with the existence of BakedSubdivMesh not that urgent (cause that one uses the ArrayMesh, MeshInstance3D combo and offers fully godot compatible data)

**Comment by fire** [comment]
>  with the existence of BakedSubdivMesh not that urgent

Not so urgent. Closing
