### ISSUE TITLE
Subdiv is not able to work on doubles

### ISSUE THREAD

**Issue by fire** [tefusion/godot-subdiv#24]
https://github.com/godotengine/godot/pull/67853

Subdiv converts a 64 bit float to 32 bit float, without converting, to opensubdiv which corrupts the attributes.

**Comment by fire** [comment]
https://github.com/v-sekai/godot-subdiv and specifically https://github.com/V-Sekai/godot-subdiv/commit/f83c83298e6a5ac02d4cd2fc8646b0d9c5b75a28 fixes.

Note that I converted the gdextension to a module.

**Comment by fire** [comment]
See also bone weight arrays.

**Comment by tefusion** [comment]
Sorry, haven't really done much with Godot cause I wanted to wait till stable release after changes broke this and other things several times in the early betas. Do you know where the problem roughly lies, I'm still quite confused with the float 64 thing, does it just allocate more memory to normal floats in code or do you need to use double to actually use it? This is why I didn't comment last time, but I can try to find the problem. 

From what I've seen you changed float->real_t a couple times, so I assume that is likely what gets defined as double when set to float64. Wouldn't it "just" (lots of places I can think of where changes are needed, if it's just baking might be easier) need to be done everywhere a public function is exposed to Godot and otherwise just cast double back to float before passing to opensubdiv and then copy back to another real_t before doing anything with Godots Rendering Servers. 

I haven't tried compiling yet cause haven't used modules so far, but I'll try a bit tomorrow and see if I can do something. A slight problem even if this change fixes it, I currently have a faster implementation using Stencil Tables on the dev branch. That one is unstable though and if I remember correctly you were mostly interested in baking so it wouldn't do much there anyway since the rough boneweights algorithm takes the longest time.

**Comment by tefusion** [comment]
So I tried it out quickly and saw you had some more changes yesterday so I think you managed to make it work. The only mesh that I had weird results with is the skinning_test.glb, but I remember that one being buggy in general because normals get generated inside.

**Comment by fire** [comment]
I got it to work, your original code was good. You may wish to do a diff and see if anything is worth moving over.

**Comment by fire** [comment]
Like `BakedSubdivMesh::_get` https://github.com/tefusion/godot-subdiv/compare/main...V-Sekai:godot-subdiv:main

**Comment by tefusion** [comment]
> Like `BakedSubdivMesh::_get` [main...V-Sekai:godot-subdiv:main](https://github.com/tefusion/godot-subdiv/compare/main...V-Sekai:godot-subdiv:main)

Thanks, already saw some stuff I can use (in importer).  I'll probably update this when Godot 4 stable comes out with one large bugfix/cleanup commit with some doc comments as well (cause I doubt I'll finish the gpu subdivision till then).
