### ISSUE TITLE
Recommend default to 8 bone weights

### ISSUE THREAD

**Issue by fire** [tefusion/godot-subdiv#7]
As godot engine only has a max of 8 bone weights, you can support both 4 and 8 by only weighting 8 weights.

**Comment by tefusion** [comment]
I needed to actively use formats because of meshes without uv's/normals anyway so I decided to leave the default to 4 and let the flag decide if 4 or 8 in 1ab3f3a333b42f4e340d4ce03844a397555e2ca4. I have not been able to find a way to trigger 8 bone weights yet so I'll leave this open (I tried blender export animation -> skinning -> include all and just got stuff godot couldn't import with a mesh with 5 bones weighted on one vertex)

**Comment by fire** [comment]
Thanks. Going to close.
