### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by fire** [tefusion/godot-subdiv#9]
I think that both I and Camille should be listed in the license as significant contributors since this code was extracted from the Godot Engine branch. See authors.md https://github.com/godotengine/godot/blob/master/AUTHORS.md

https://github.com/fire K. S. Ernest (iFire) Lee (fire) https://github.com/godot-extended-libraries/godot-fire/tree/feature/3.2/opensubdiv-next

https://github.com/pouleyKetchoupp Camille Mohr-Daurat (pouleyKetchoupp) wrote the original proposal https://github.com/godotengine/godot-proposals/issues/784

**Comment by tefusion** [comment]
Right, sorry. I was/am unsure if I can just list people as contributors, I should've just asked... I have no idea about licensing. Do you mean I should create an AUTHORS file like godot then and put those 2 lines a little bit edited at the top?

**Comment by fire** [comment]
I'm ok with it. I don't think @pouleyKetchoupp is in the Godot Engine ecosystem anymore.

Alternatively you can copy the Godot Engine license as is.

**Comment by tefusion** [comment]
The function naming and functionality of the QuadMeshInstance and the mesh are planned to be an exact copy of the corresponding one in Godot so I think the Godot license is needed as well. I'll do the authors thing for now because I do want to credit you (I do in the README just not in the more important License)

**Comment by pouleyKetchoupp** [comment]
Thanks! I would be happy to be credited as well :)

Also excellent work on making this plugin! It's a great idea, will be easier than convincing maintainers to add subdiv support to core.

**Comment by tefusion** [comment]
I made a quick AUTHORS file for now, might change tomorrow cause I'm not fully happy with my wording. It gets included in the artifact as well :) 


> Thanks! I would be happy to be credited as well :)
> 
> Also excellent work on making this plugin! It's a great idea, will be easier than convincing maintainers to add subdiv support to core.

Thanks a lot!  It's been quite fun developing this so far since this is my first actual C++ project (just did small stuff before). I likely would've not started this without your proposal :smile:, so thanks!

**Comment by fire** [comment]
Closing as resolved.
